"""Add YouTube models

Revision ID: 373e14130927
Revises: 7
Create Date: 2026-02-23 12:58:15.908313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '373e14130927'
down_revision: Union[str, None] = '7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_videos_id'), 'youtube_videos', ['id'], unique=False)
    op.create_index(op.f('ix_youtube_videos_video_id'), 'youtube_videos', ['video_id'], unique=True)
    op.create_table('user_youtube_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_youtube_videos_id'), 'user_youtube_videos', ['id'], unique=False)
    op.create_index(op.f('ix_user_youtube_videos_user_id'), 'user_youtube_videos', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_youtube_videos_video_id'), 'user_youtube_videos', ['video_id'], unique=False)
    op.alter_column('cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('decks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('review_log', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('writing_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_writing_submissions_created_at', table_name='writing_submissions')
    op.drop_index('ix_writing_submissions_user_id', table_name='writing_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_writing_submissions_user_id', 'writing_submissions', ['user_id'], unique=False)
    op.create_index('ix_writing_submissions_created_at', 'writing_submissions', ['created_at'], unique=False)
    op.alter_column('writing_submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('review_log', 'reviewed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('decks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_user_youtube_videos_video_id'), table_name='user_youtube_videos')
    op.drop_index(op.f('ix_user_youtube_videos_user_id'), table_name='user_youtube_videos')
    op.drop_index(op.f('ix_user_youtube_videos_id'), table_name='user_youtube_videos')
    op.drop_table('user_youtube_videos')
    op.drop_index(op.f('ix_youtube_videos_video_id'), table_name='youtube_videos')
    op.drop_index(op.f('ix_youtube_videos_id'), table_name='youtube_videos')
    op.drop_table('youtube_videos')
    # ### end Alembic commands ###
