"""add_ielts_exam_parts

Revision ID: 434acd4748de
Revises: 373e14130927
Create Date: 2026-02-23 23:01:58.359730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '434acd4748de'
down_revision: Union[str, None] = '373e14130927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ielts_exam_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('part_number', sa.Integer(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['youtube_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ielts_exam_parts_id'), 'ielts_exam_parts', ['id'], unique=False)
    op.create_index(op.f('ix_ielts_exam_parts_part_number'), 'ielts_exam_parts', ['part_number'], unique=False)
    op.create_index(op.f('ix_ielts_exam_parts_video_id'), 'ielts_exam_parts', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ielts_exam_parts_video_id'), table_name='ielts_exam_parts')
    op.drop_index(op.f('ix_ielts_exam_parts_part_number'), table_name='ielts_exam_parts')
    op.drop_index(op.f('ix_ielts_exam_parts_id'), table_name='ielts_exam_parts')
    op.drop_table('ielts_exam_parts')
    # ### end Alembic commands ###
